# Generated by Django 3.0.6 on 2021-01-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('student', models.BooleanField(default=False)),
                ('judge', models.BooleanField(default=False)),
                ('coach', models.BooleanField(default=False)),
                ('school', models.TextField(null=True)),
                ('verified', models.BooleanField(default=False)),
                ('verification_code', models.TextField()),
                ('elo', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(default='ananymous', max_length=120)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('bio', models.TextField(blank=True, default=None, null=True)),
                ('banner', models.FileField(default='banner', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('doc_name', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('round_no', models.CharField(max_length=6)),
                ('team1', models.CharField(max_length=120)),
                ('team2', models.CharField(blank=True, max_length=120, null=True)),
                ('winner', models.CharField(blank=True, max_length=120, null=True)),
                ('judge', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('adult_name', models.CharField(max_length=120)),
                ('adult_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adult_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Speaker_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('round_no', models.CharField(max_length=6)),
                ('participant', models.EmailField(max_length=254)),
                ('points', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Team_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('round_no', models.CharField(max_length=6)),
                ('team_name', models.CharField(max_length=120)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team_statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('team_name', models.CharField(max_length=120)),
                ('wins', models.CharField(default=0, max_length=2)),
                ('losses', models.CharField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('host', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('n_rounds', models.CharField(max_length=6)),
                ('street', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('pin_code', models.CharField(max_length=6)),
                ('min_students', models.CharField(default=2, max_length=6)),
                ('max_students', models.CharField(max_length=6)),
                ('max_teams', models.CharField(max_length=2)),
                ('break_round', models.CharField(max_length=14)),
                ('reg_deadline', models.DateField()),
                ('speaker_point_show', models.BooleanField(default=True)),
                ('only_school_judge', models.BooleanField(default=False)),
                ('private', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments_participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('school_name', models.CharField(max_length=120)),
                ('team_name', models.CharField(max_length=120)),
                ('acc_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('school_name', models.CharField(max_length=120)),
                ('supervisor_name', models.TextField(max_length=150)),
                ('supervisor_number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments_team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=150)),
                ('school_name', models.CharField(max_length=120)),
                ('team_name', models.CharField(max_length=120)),
            ],
        ),
    ]
